### ISSUE TITLE
HardSwish operator is still not supported in version 0.5.0

### ISSUE THREAD

**Issue by javanli** [Talmaj/onnx2pytorch#71]
hi
There seems to be something wrong with tag 0.5.0.
it(16125eb) is on the develop branch insted of master, and some new commits are not included, like HardSwish support.

**Comment by javanli** [comment]
@Talmaj

**Comment by Talmaj** [comment]
@javanli thanks for noticing that! I am looking into it

**Comment by Talmaj** [comment]
@javanli I released a new version, this one should have it.
